### ISSUE TITLE
MM DropTable with MMOItems don't work.

### ISSUE THREAD

**Issue by honnisha** [Seyarada/PandeLootPlus#3]
Drop from MM DropTable doesn't spawn MMOItems:
```
sz1:
  Type: ZOMBIE
  Rewards:
    - droptable:LootStart{top=1;damage=20%}
```

In file:
https://github.com/Seyarada/PandeLootPlus/blob/master/Plugin/src/main/java/net/seyarada/pandeloot/compatibility/mythicmobs/DropTableCompatibility.java

mmoitem appears as CustomDrop:
```
        for (Drop drop : drops) {
            double amount = drop.getAmount();
            if (drop instanceof CustomDrop customDrop) {
                if (customDrop.getDrop().get() instanceof IItemDrop itemDrop) {
                    AbstractItemStack stack = itemDrop.getDrop(meta, amount);
                    ...
                }
            }
            else if (drop instanceof IItemDrop itemDrop) {
                ...
            }
            else {
                Can you add log incase conditiond dont cover all loot cases?
            }
        }
```

I can't create pull request because I can't compile plugin because of:
```The POM for org.spigotmc:spigot:jar:remapped-mojang:1.17.1-R0.1-SNAPSHOT is missing, no dependency information available```

Thank you!

**Comment by Seyarada** [comment]
Should be added/fixed in newest :D
